

```plantuml
@startuml
actor Cliente
participant Servidor

Cliente -> Servidor: Conectar (Socket)
activate Servidor
Cliente -> Servidor: Enviar nombre


Servidor -> Servidor: Esperar 3 segundos
note over Servidor: Comienza la partida

loop Mientras partidaTerminada == false
    Servidor -> Cliente: Enviar puntaje aleatorio(x veces del 1 al 10)
    Servidor -> Servidor: Comprobar puntuación
end
        Servidor -> Cliente: Enviar "¡Felicidades NOMBRE! Has ganado la carrera."
        Servidor -> Cliente: Enviar "El ganador es: NOMBRE" 
        Servidor -> Servidor: Terminar juego

Cliente -> Servidor: Cerrar conexión
deactivate Servidor
@enduml